dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: ONd0AVDSd28SEYkII6X45XUdHiSd9P8FAesgzKxg8qNydOFO6Z7t81veWdYiKK+WtZ3v+cfhq5x+7lGraXrC72JmlQ5eTE3ZPulp9xB5cdgn2TEvtt7y4Am6prPVwAHiPvdgXXJxkiqGdpoknU0MhgGF/w+yf1MNMH2sa6Y3GJzk8vLSj3jS0xZsU1j9rEtcHvUzB6PGYga9NdMNL5n5zZ64cYdlJIivRYxKP4g/1xz6d7JkOBVnXzxTkgWM8ruB5z65lOGOA+9y6m2Kk35Rw+fot+6G2PoUjfSePBbkT+6Gn4tckqSzUNRGhbIIOKJuNOX95+C2wvIKKCzXEETuTypTv/iHeIbE3cOjlvGzaojVkwZ1CgRCgcT2vtat8g2Em6TN4qfxw2d47tcN6PcXJ790ZwGC06sGX2hYKAo2354VcsBqPpzMtFZAIQTLkD+gFZbQRjxsMtGq6JWNv0UOmxqK6qi0nMxGX+aCqGp2jfxnOqNxCmY+ISa8AOaMhyAB0HgNhNBgms9peWXmEIYlJJI9zEMI9Kbs69OtucF3gzmciucaR6kPCLCXwmrlumjz7HJ2Bq6W5H+L9r5F4p7HMQVK4fOuztK+wwxtEJA326VBy+vEfbArj6MFMtYWzNZrRMB9GW0haL+vfbajiHRDmEas+0hfR8nHIkVBM0wDgQU=
  file: Gerbers/PIN-113_gerbers.zip
  on:
    repo: w4xzr/PIN-113
  skip_cleanup: 'true'
